name: Format Check

on: push

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0

      - name: Check Format
        run: devbox run fmt && git update-index --really-refresh && git diff-index --quiet HEAD
